default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: README.md
        args: ["--profile", "black"]

  # temporarily disable static type checking
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.2.0
  #   hooks:
  #     - id: mypy
  #       args: ["--ignore-missing-imports", "--scripts-are-modules", "--pretty"]
