name: "prolificdreamer-propnet"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0

data_type: "random-camera-datamodule"
data:
  batch_size: [1, 1]
  # 0-4999: 64x64, >=5000: 512x512
  # this drastically reduces VRAM usage as empty space is pruned in early training
  width: [64, 512]
  height: [64, 512]
  resolution_milestones: [5000]
  camera_distance_range: [1.0, 1.5]
  fovy_range: [40, 70]
  elevation_range: [-10, 45]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 1.5
  eval_fovy_deg: 70.

system_type: "prolificdreamer-system"
system:
  stage: coarse
  geometry_type: "implicit-volume"
  geometry:
    radius: 1.0
    normal_type: null

    density_bias: blob_magic3d
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

  material_type: no-material
  material:
    n_output_dims: 3
    color_activation: sigmoid

  background_type: neural-environment-map-background
  background:
    color_activation: sigmoid
    random_aug: true

  renderer_type: nerf-volume-renderer
  renderer:
    radius: ${system.geometry.radius}
    estimator: proposal
    num_samples_per_ray: 32
    num_samples_per_ray_proposal: 64
    near_plane: 0.1
    far_plane: 4.0
    proposal_network_config:
      n_input_dims: 3
      n_output_dims: 1
      encoding_config:
        otype: HashGrid
        n_levels: 5
        n_features_per_level: 2
        log2_hashmap_size: 17
        base_resolution: 16
        per_level_scale: 1.681792830507429 # max_resolution: 128
      network_config:
        otype: VanillaMLP
        activation: ReLU
        output_activation: none
        n_neurons: 64
        n_hidden_layers: 1
    prop_optimizer_config:
      name: Adam
      args:
        lr: 1.0e-2
        eps: 1.0e-15
        weight_decay: 1.0e-6
    prop_scheduler_config:
      name: ChainedScheduler
      schedulers:
        - name: LinearLR
          args:
            start_factor: 0.01
            total_iters: 100
        # -
        #   name: MultiStepLR
        #   args:
        #     milestones:
        #       - ${idiv:${trainer.max_steps},2}
        #       - ${idiv:${mul:${trainer.max_steps},3},4}
        #       - ${idiv:${mul:${trainer.max_steps},9},10}
        #     gamma: 0.33

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???
    front_threshold: 30.
    back_threshold: 30.

  guidance_type: "stable-diffusion-vsd-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path_lora: "stabilityai/stable-diffusion-2-1"
    guidance_scale: 7.5
    min_step_percent: 0.02
    max_step_percent: [5000, 0.98, 0.5, 5001] # annealed to 0.5 after 5000 steps

  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_vsd: 1.
    lambda_lora: 1.
    lambda_orient: 0.
    lambda_sparsity: 10.
    lambda_opaque: [10000, 0.0, 1000.0, 10001]
    lambda_z_variance: 0.
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.density_network:
        lr: 0.001
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001
      guidance:
        lr: 0.0001

trainer:
  max_steps: 25000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 32

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
