NAME="firekeeper"
GPU=0

# zero123, XL
python launch.py --config configs/zero123.yaml --train --gpu $GPU data.image_path=./load/images/${NAME}_rgba.png system.guidance.pretrained_model_name_or_path="./load/zero123/XL_20230604.ckpt" use_timestamp=False name=${NAME}_DEMO tag="XL_Phase1" system.loggers.wandb.enable=true system.loggers.wandb.project="voletiv-zero123XL-demo-NEW" system.loggers.wandb.name=${NAME}_XL_Phase1; python launch.py --config configs/zero123-geometry.yaml --train --gpu $GPU data.image_path=./load/images/${NAME}_rgba.png system.guidance.pretrained_model_name_or_path="./load/zero123/XL_20230604.ckpt" system.geometry_convert_from=./outputs/${NAME}_DEMO/XL_Phase1/ckpts/last.ckpt use_timestamp=False name=${NAME}_DEMO tag="XL_Phase1p5" system.loggers.wandb.enable=true system.loggers.wandb.project="voletiv-zero123XL-demo-NEW" system.loggers.wandb.name=${NAME}_XL_Phase1p5

# zero123, OLD
python launch.py --config configs/zero123.yaml --train --gpu $GPU data.image_path=./load/images/${NAME}_rgba.png system.guidance.pretrained_model_name_or_path="./load/zero123/105000.ckpt" use_timestamp=False name=${NAME}_DEMO tag="OLD_Phase1" system.loggers.wandb.enable=true system.loggers.wandb.project="voletiv-zero123XL-demo-NEW" system.loggers.wandb.name=${NAME}_OLD_Phase1; python launch.py --config configs/zero123-geometry.yaml --train --gpu $GPU data.image_path=./load/images/${NAME}_rgba.png system.guidance.pretrained_model_name_or_path="./load/zero123/105000.ckpt" system.geometry_convert_from=./outputs/${NAME}_DEMO/OLD_Phase1/ckpts/last.ckpt use_timestamp=False name=${NAME}_DEMO tag="OLD_Phase1p5" system.loggers.wandb.enable=true system.loggers.wandb.project="voletiv-zero123XL-demo-NEW" system.loggers.wandb.name=${NAME}_OLD_Phase1p5

# zero123_64, XL
python launch.py --config configs/zero123_64.yaml --train --gpu $GPU data.image_path=./load/images/${NAME}_rgba.png system.guidance.pretrained_model_name_or_path="./load/zero123/XL_20230604.ckpt" use_timestamp=False name=${NAME}_DEMO tag="XL_64_Phase1" system.loggers.wandb.enable=true system.loggers.wandb.project="voletiv-zero123XL-demo-NEW" system.loggers.wandb.name=${NAME}_XL_64_Phase1; python launch.py --config configs/zero123-geometry.yaml --train --gpu $GPU data.image_path=./load/images/${NAME}_rgba.png system.guidance.pretrained_model_name_or_path="./load/zero123/XL_20230604.ckpt" system.geometry_convert_from=./outputs/${NAME}_DEMO/XL_64_Phase1/ckpts/last.ckpt use_timestamp=False name=${NAME}_DEMO tag="XL_64_Phase1p5" system.loggers.wandb.enable=true system.loggers.wandb.project="voletiv-zero123XL-demo-NEW" system.loggers.wandb.name=${NAME}_XL_64_Phase1p5

# zero123_64, OLD
python launch.py --config configs/zero123_64.yaml --train --gpu $GPU data.image_path=./load/images/${NAME}_rgba.png system.guidance.pretrained_model_name_or_path="./load/zero123/105000.ckpt" use_timestamp=False name=${NAME}_DEMO tag="OLD_64_Phase1" system.loggers.wandb.enable=true system.loggers.wandb.project="voletiv-zero123XL-demo-NEW" system.loggers.wandb.name=${NAME}_OLD_64_Phase1; python launch.py --config configs/zero123-geometry.yaml --train --gpu $GPU data.image_path=./load/images/${NAME}_rgba.png system.guidance.pretrained_model_name_or_path="./load/zero123/105000.ckpt" system.geometry_convert_from=./outputs/${NAME}_DEMO/OLD_64_Phase1/ckpts/last.ckpt use_timestamp=False name=${NAME}_DEMO tag="OLD_64_Phase1p5" system.loggers.wandb.enable=true system.loggers.wandb.project="voletiv-zero123XL-demo-NEW" system.loggers.wandb.name=${NAME}_OLD_64_Phase1p5
