python launch.py --config configs/gaussian_splatting.yaml --train --gpu 0 name=gaussian_splatting tag=v1 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes"

# python launch.py --config configs/gaussian_splatting.yaml --train --gpu 0 name=gaussian_splatting tag=v1 system.prompt_processor.prompt="a delicious hamburger"
python launch.py --config configs/gaussian_splatting_editing.yaml --train --gpu 0 data.dataroot="load/twindom" name=gaussian_splatting_editing tag=v1 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes"

# gaussian
python launch.py --config configs/gaussian_dynamic.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian tag=v1 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes" data.eval_interpolation=[0,20,10] data.eval_time_interpolation=[0.0,0.8]

python launch.py --config configs/gaussian_dynamic.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian tag=v1 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes" data.eval_interpolation=[0,20,10] data.eval_time_interpolation=[0.0,0.8] resume=/root/autodl-tmp/threestudio/outputs/dynamic_gaussian/v1@20231015-221401/ckpts/last.ckpt

python launch.py --config configs/gaussian_dynamic.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian tag=v1 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes" data.eval_interpolation=[0,3,40] data.eval_time_interpolation=[0.0,0.8] resume=/root/autodl-tmp/threestudio/outputs/dynamic_gaussian/v1@20231016-194337/ckpts/epoch=0-step=50000.ckpt

python launch.py --config configs/dynamic_nerf.yaml --train --gpu 0  data.dataroot="load/twindom_dynamic" name=dynamic_nerf tag=v1 system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes" data.eval_interpolation=[0,20,10] data.eval_time_interpolation=[0.0,0.8]

python launch.py --config configs/dynamic_control4d.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_control4d system.prompt_processor.prompt="a zoomed out DSLR photo of a baby bunny sitting on top of a stack of pancakes" data.eval_interpolation=[0,3,40] data.eval_time_interpolation=[0.0,0.8]

python launch.py --config configs/dynamic_gaussian_instruct.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian tag=v1 system.prompt_processor.prompt="Turn him into Elon Musk"
python launch.py --config configs/dynamic_gaussian_instruct.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian tag=v1 data.camera_layout="front" data.camera_distance=1.0 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[0,1,40] data.eval_time_interpolation=[0.0,0.8]

python launch.py --config configs/dynamic_gaussian_reconstruct.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian_reconstruct tag=v1 data.camera_layout="front" data.camera_distance=1.0 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[10,11,40] data.eval_time_interpolation=[0.0,0.8]
python launch.py --config configs/dynamic_gaussian_instruct.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian_instruct tag=v1 data.camera_layout="front" data.camera_distance=1.0 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[10,11,40] data.eval_time_interpolation=[0.0,0.8] resume=/root/autodl-tmp/threestudio/outputs/dynamic_gaussian_reconstruct/v1@20231019-214518/ckpts/last.ckpt
python launch.py --config configs/dynamic_gaussian_volume_instruct.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian_instruct tag=v1 data.camera_layout="front" data.camera_distance=1.0 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[10,11,40] data.eval_time_interpolation=[0.0,0.8] system.geometry.geometry_convert_from=/root/autodl-tmp/threestudio/outputs/dynamic_gaussian_reconstruct/v1@20231019-214518/ckpts/last.ckpt

python launch.py --config configs/dynamic_gaussian_reconstruct.yaml --train --gpu 0 data.dataroot="load/yxd-t4d" name=dynamic_gaussian_reconstruct tag=yxd data.camera_layout="front" data.camera_distance=2.0 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[2,3,40] data.eval_time_interpolation=[0.0,0.8]

python launch.py --config configs/instructnerf2nerf.yaml --train --gpu 0 data.dataroot="load/yxd-t4d" name=nerf_reconstruct tag=yxd data.camera_layout="front" data.camera_distance=1.5 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[2,3,20]
python launch.py --config configs/instructnerf2nerf.yaml --train --gpu 0 data.dataroot="load/face" name=nerf_reconstruct tag=face data.camera_layout="front" data.camera_distance=1.0 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[0,8,20]

python launch.py --config configs/dynamic_gaussian_reconstruct.yaml --train --gpu 0 data.dataroot="load/face" name=gaussian_reconstruct tag=face data.camera_layout="front" data.camera_distance=2.5 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[0,8,20]  data.eval_time_interpolation=[0.0,0.0]

python launch.py --config configs/dynamic_gaussian_reconstruct.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian_reconstruct tag=v1 data.camera_layout="front" data.camera_distance=1.5 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[0,11,40] data.eval_time_interpolation=[0.0,0.0]
python launch.py --config configs/dynamic_gaussian_reconstruct.yaml --train --gpu 0 data.dataroot="load/twindom_dynamic" name=dynamic_gaussian_reconstruct tag=v1 data.camera_layout="front" data.camera_distance=1.5 system.prompt_processor.prompt="Elon Musk wearing white shirt"

python launch.py --config configs/dynamic_gaussian_reconstruct.yaml --train --gpu 0 data.dataroot="load/yxd-t4d" name=dynamic_gaussian_reconstruct tag=yxd data.camera_layout="front" data.camera_distance=1.5 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[2,3,20] data.eval_time_interpolation=[0.0,0.8]
python launch.py --config configs/dynamic_gaussian_volume_instruct.yaml --train --gpu 0 data.dataroot="load/yxd-t4d" name=dynamic_gaussian_instruct tag=yxd data.camera_layout="front" data.camera_distance=1.5 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[2,3,40] data.eval_time_interpolation=[0.0,0.8] system.geometry.geometry_convert_from=/root/autodl-tmp/threestudio/outputs/dynamic_gaussian_reconstruct/yxd@20231021-184742/ckpts/last.ckpt
python launch.py --config configs/dynamic_gaussian_volume_instruct.yaml --train --gpu 0 data.dataroot="load/yxd-t4d" name=dynamic_gaussian_instruct tag=yxd data.camera_layout="front" data.camera_distance=1.5 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[2,3,80] data.eval_time_interpolation=[0.0,1.0] system.geometry.geometry_convert_from=/root/autodl-tmp/threestudio/outputs/dynamic_gaussian_reconstruct/yxd@20231021-184742/ckpts/last.ckpt
python launch.py --config configs/dynamic_gaussian_volume_instruct.yaml --train --gpu 0 data.dataroot="load/yxd-t4d" name=dynamic_gaussian_instruct tag=yxd data.camera_layout="front" data.camera_distance=1.5 system.prompt_processor.prompt="Realistic Robot" data.eval_interpolation=[2,3,80] data.eval_time_interpolation=[0.0,1.0] system.geometry.geometry_convert_from=/root/autodl-tmp/threestudio/outputs/dynamic_gaussian_reconstruct/yxd@20231021-184742/ckpts/last.ckpt

python launch.py --config configs/dynamic_gaussian_reconstruct.yaml --train --gpu 0 data.dataroot="load/enerf_actor1" name=dynamic_gaussian_reconstruct tag=enerf data.camera_layout="front" data.camera_distance=4.0 system.prompt_processor.prompt="Elon Musk wearing white shirt" data.eval_interpolation=[0,7,20] data.eval_time_interpolation=[0.0,0.0]
python launch.py --config configs/dynamic_gaussian_volume_instruct.yaml --train --gpu 0 data.dataroot="load/enerf_actor1" name=dynamic_gaussian_instruct tag=enerf data.camera_layout="front" data.camera_distance=4.0 system.prompt_processor.prompt="Elon Musk wearing causual clothes" data.eval_interpolation=[0,7,20] data.eval_time_interpolation=[0.0,0.0] system.guidance.fixed_size=0 system.geometry.geometry_convert_from=/root/autodl-tmp/threestudio/outputs/dynamic_gaussian_reconstruct/enerf@20231021-234113/ckpts/last.ckpt
