# BLA26: same as BLA25 except `elevation_range: [-10, 80]`
threestudio/scripts/run_zero123_phase.sh 1 anya_front XL_20230604 0 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 2 baby_phoenix_on_ice XL_20230604 20 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 3 beach_house_1 XL_20230604 50 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 4 bollywood_actress XL_20230604 0 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 5 beach_house_2 XL_20230604 30 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 6 hamburger XL_20230604 10 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 7 cactus XL_20230604 8 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 0 catstatue XL_20230604 50 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 1 church_ruins XL_20230604 0 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 2 firekeeper XL_20230604 10 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 3 futuristic_car XL_20230604 20 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 4 mona_lisa XL_20230604 10 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
threestudio/scripts/run_zero123_phase.sh 5 teddy XL_20230604 20 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999

# with standard zero123
threestudio/scripts/run_zero123_phase.sh 6 anya_front 105000 0 system.loss.lambda_3d_normal_smooth=2.0 system.geometry.pos_encoding_config.otype=HashGrid system.loss.lambda_normal_smooth=5.0 system.loss.lambda_sds=0.03 data.height=128 data.width=128 data.random_camera.batch_size=12 data.random_camera.height=64 data.random_camera.width=64 system.loss.lambda_depth=0.05 system.loss.lambda_sparsity=0.1 system.loss.lambda_rgb=500.0 system.loss.lambda_opaque=0.05 system.loss.lambda_orient=1.0 system.optimizer.args.lr=0.05 trainer.max_steps=1999
